### ISSUE TITLE
don't work toggle button of summary view display from Gitbook V2.5.x

### ISSUE THREAD

**Issue by yoshidax** [yoshidax/gitbook-plugin-summary-splitter#4]

**Comment by TakahiRoyte** [comment]
Pressing toggle button may cause side menu to disappear.
If it happens, try clearing datas in your localstorage of browser.
It will reset the setting and the side menu should appear again.

http://www.ghacks.net/2015/02/05/how-to-clear-web-storage-in-your-browser-of-choice/

**Comment by yoshidax** [comment]
@TakahiRoyte 
Thank you for help :smiley:
