### ISSUE TITLE
Mobile Content Does not Slide

### ISSUE THREAD

**Issue by hallahan** [yoshidax/gitbook-plugin-summary-splitter#6]
I found a bug in mobile (Android Chrome) When clicking on a link in the summary panel, the panel will disappear, but the main content will not move back to the left. You have to click on the menu button to get the summary panel back. Clicking explicitly on the menu button again will move the main content to the left like it should do.

**Comment by yoshidax** [comment]
@hallahan 

Since this plugin is not necessary for mobile, we will try to disable it on mobile.
I will respond so that it will not work on mobile soon.

Thank you for the report. 👍

**Comment by yoshidax** [comment]
done
