### ISSUE TITLE
Is your side of the side of the directory is folded with what plug-ins it? Quite good-looking

### ISSUE THREAD

**Issue by zq99299** [yoshidax/gitbook-plugin-summary-splitter#8]
Is your side of the side of the directory is folded with what plug-ins it? Quite good-looking
请问你的侧边目录折叠是用的什么插件呢？挺好看的

**Comment by yoshidax** [comment]
that plugin is [gitbook-plugin-expandable-chapters](https://github.com/DomainDrivenArchitecture/gitbook-plugin-expandable-chapters).
are you ok?
